### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by natethemaker** [Calastrophe/Discord-Token-Bruteforcer-Helper#4]
this python thing spams this error now
```
AttributeError: module 'strgen' has no attribute 'StringGenerator'
```

**Comment by QuartzWarrior** [comment]
You installed the wrong one, do `pip install StringGenerator`

**Comment by pythoncmd** [comment]
I tried to use pip install StringGenerator but i still got the error "module 'strgen' has no attribute 'StringGenerator'"

**Comment by QuartzWarrior** [comment]
Did you run `pip uninstall strgen` before you did that? If not, then run it.

**Comment by Calastrophe** [comment]
You incorrectly installed dependencies, obviously.
